### PR TITLE
[BUG] Enable setting review notifications without delegation

### LINKED ISSUE #2273: [BUG]: Allow setting review notifications without delegation
### Expected Behavior

It should be possible to set `github_team_settings.review_request_delegation.notify` without enabling auto assignment.

These are independent settings:
image

### Actual Behavior

When only setting `notify`, `terraform apply` fails with
```
Error: Review request delegation member count must be greater than 0
```

### Terraform Version

Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.39.0

### Affected Resource(s)

- `github_team_settings`

### Terraform Configuration Files

_No response_

### Steps to Reproduce

_No response_

### Debug Output

_No response_

### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deiga**
Resolves #2273

----

### Before the change?

- Docs for `github_team_settings` we're missing computed attributes
- Tests didn't cover all behaviour
- Tests used legacy `Check:` structure
- Resource didn't use Context-aware CRUD functions
- Resource CRUD-functions we're tightly coupled
- It was not possible to set an empty `review_request_delegation` block
- It wasn't possible to set `notify` without enabling delegation

### After the change?

- Docs for `github_team_settings` are complete
- Tests cover all behaviour
- Tests use new check structures from `terraform-plugin-testing`
- Resource uses Context-aware CRUD functions
- Resource CRUD-functions are independent
- It is possible to set an empty `review_request_delegation` block
- It is possible to set `notify` without enabling delegation

### Pull request checklist

- [ ] Schema migrations have been created if needed ([example](https://github.com/F-Secure-web/terraform-provider-github/blob/main/github/migrate_github_actions_organization_secret.go))
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

File: github/resource_github_team_settings.go [hunk 1]
```diff
@@ -201,7 +305,7 @@ func resourceGithubTeamSettingsImport(d *schema.ResourceData, meta any) ([]*sche
 	if err = d.Set("team_uid", nodeId); err != nil {
 		return nil, err
 	}
-	return []*schema.ResourceData{d}, resourceGithubTeamSettingsRead(d, meta)
+	return []*schema.ResourceData{d}, nil
 }
 
 func resolveTeamIDs(idOrSlug string, meta *Owner, ctx context.Context) (nodeId, slug string, err error) {
```
Comment (stevehipwell) [inline github/resource_github_team_settings.go]:
```suggestion
func resolveTeamIDs(ctx context.Context, meta *Owner, idOrSlug string) (nodeId, slug string, err error) {
```
Do you want to fix this signature while we're here?

Comment (deiga) [reply github/resource_github_team_settings.go]: Sure!

Comment (stevehipwell) [reply github/resource_github_team_settings.go]: Other than this the PR looks good, I'll give it a final review after you push this.

**Review by stevehipwell — DISMISSED** [review]
LGTM

**Review by robert-crandall — DISMISSED** [review]

**Comment by stevehipwell** [comment]
@deiga could you please rebase this?

**Comment by deiga** [comment]
@stevehipwell @robert-crandall Rebased, please review.
I'll review the others as well, but will wait for this to be merged before asking for reviews there

**Review by robert-crandall — DISMISSED** [review]

File: github/resource_github_team_settings.go [hunk 2]
```diff
@@ -201,37 +303,39 @@ func resourceGithubTeamSettingsImport(d *schema.ResourceData, meta any) ([]*sche
...
-	} else {
-		// The given id is an integer, assume it is a team id
-		team, _, teamIdErr := client.Teams.GetTeamByID(ctx, orgId, teamId)
-		if teamIdErr != nil {
-			// There isn't a team with the given ID, assume it is a teamslug
-			team, _, slugErr := client.Teams.GetTeamBySlug(ctx, orgName, idOrSlug)
-			if slugErr != nil {
-				return "", "", errors.New(teamIdErr.Error() + slugErr.Error())
-			}
+func resolveTeamIDs(ctx context.Context, meta *Owner, idOrSlug string) (nodeId, slug string, err error) {
```
Comment (stevehipwell) [inline github/resource_github_team_settings.go]:
```suggestion
func resolveTeamIDs(ctx context.Context, meta *Owner, idOrSlug string) (string, string, error) {
```
Could you please remove the named returns?

File: github/resource_github_team_settings.go [hunk 3]
```diff
@@ -201,37 +303,39 @@ func resourceGithubTeamSettingsImport(d *schema.ResourceData, meta any) ([]*sche
...
 
-			return team.GetNodeID(), team.GetSlug(), nil
-		}
+// resolveNotify returns the notify value from the top-level attribute or the
+// deprecated nested attribute inside review_request_delegation. The top-level
+// attribute takes precedence. Since ConflictsWith prevents both from being set,
+// only one source can be active at a time.
+func resolveNotify(ctx context.Context, d *schema.ResourceData) bool {
+	// Check if top-level notify is explicitly configured.
+	if v, ok := d.GetOk("notify"); ok {
```
Comment (stevehipwell) [inline github/resource_github_team_settings.go]: I'm not sure there is any value to using `GetOk()` here given the way it works and the fact that you're using an explicit schema?

**Review by stevehipwell — CHANGES_REQUESTED** [review]
Just a couple of things to look at.

File: github/resource_github_team_settings.go (hunk 3 above)
Comment (deiga) [reply github/resource_github_team_settings.go]: The way I understand the code is that this is exactly where `GetOk()` should work for `TypeBool`. 
It should check if `notify` has been set in the config, right? Of course the tests don't have that scenario at all 🙃

Comment (deiga) [reply github/resource_github_team_settings.go]: Or how else would I be checking which one of the fields is actually set? Should I just read both and see if either is true? That sounds simpler 🤔

File: github/resource_github_team_settings.go [hunk 4]
```diff
@@ -115,66 +184,95 @@ func resourceGithubTeamSettingsRead(d *schema.ResourceData, meta any) error {
...
+			settings := reviewRequestDelegation[0].(map[string]any)
 
 			teamReviewAlgorithm := githubv4.TeamReviewAssignmentAlgorithm(settings["algorithm"].(string))
-			return graphql.Mutate(ctx, &mutation, githubv4.UpdateTeamReviewAssignmentInput{
+			updateTeamReviewAssignmentInput := githubv4.UpdateTeamReviewAssignmentInput{
 				ID:              d.Id(),
 				Enabled:         githubv4.Boolean(true),
 				Algorithm:       &teamReviewAlgorithm,
 				TeamMemberCount: new(githubv4.Int(settings["member_count"].(int))),
 				NotifyTeam:      new(githubv4.Boolean(settings["notify"].(bool))),
```
Comment (robert-crandall) [inline github/resource_github_team_settings.go]: Should this use the new `resolveNotify` instead of the legacy field?

File: github/resource_github_team_settings.go (hunk 3 above)
Comment (stevehipwell) [reply github/resource_github_team_settings.go]: Ideally you read them and look for `true`, if you can't do that then you need to fallback to using a hack like we had to use on some of the repo fields.

**Review by robert-crandall — DISMISSED** [review]

File: github/resource_github_team_settings.go (hunk 3 above)
Comment (deiga) [reply github/resource_github_team_settings.go]: Yeah, I'll check that out. Too long since this discussion was had :D

**Comment by deiga** [comment]
@stevehipwell Thanks. Simplified the bool checking a bit now

**Review by stevehipwell — APPROVED** [review]
LGTM

**Comment by stevehipwell** [comment]
@robert-crandall please could you approve this.

**Review by robert-crandall — APPROVED** [review]
