### PR TITLE
[BUG] `github_organization_role` Ensure `role_id` is set after Create

### LINKED ISSUE #3004: [BUG]: github_organization_role setting base_role = "none" causes permanent diff
### Expected Behavior

Given a configuration like
```
resource "github_organization_role" "audit_viewer" {
  name        = "Audit Viewer"
  description = "Access the Organization Audit Log"
  base_role   = "none"
  permissions = [
    "read_audit_logs"
  ]
}
```
it should get applied once and on subsequent plans do not cause any diff.

### Actual Behavior

```
Terraform will perform the following actions:
  # github_organization_role.audit_viewer will be updated in-place
  ~ resource "github_organization_role" "audit_viewer" ***
      + base_role   = "none"
        id          = "12345"
        name        = "Audit Viewer"
        # (3 unchanged attributes hidden)
    ***
Plan: 0 to add, 1 to change, 0 to destroy.
```

That change is applied on every subsequent run.

### Terraform Version

```
$ terraform -v
Terraform v1.14.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v7.13.0
+ provider registry.terraform.io/hashicorp/googleworkspace v0.7.0
+ provider registry.terraform.io/integrations/github v6.9.0
```

### Affected Resource(s)

- github_organization_role

### Terraform Configuration Files

```hcl

```

### Steps to Reproduce

Run `terraform apply` twice or more.

### Debug Output

```shell

```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #3009: [BUG]: `github_organization_role_team` doesn't wait for role_id
### Expected Behavior

When creating a `github_organization_role`-resource and trying to use the `role_id` afterwards, the resource fails with the following error:
```
│   43:   role_id   = github_organization_role.example.role_id
│ 
│ The argument "role_id" is required, but no definition was found.
```
When re-runing apply with the created `github_organization_role` (from first run) it finds the `role_id`.

I would expect the resource to provide the `role_id` also when creating.

### Actual Behavior

See above

### Terraform Version

Terraform v1.11.4
on darwin_arm64

### Affected Resource(s)

- github_organization_role_team

### Terraform Configuration Files

```hcl
resource "github_organization_role" "example" {
  name      = "Example Reader"
  base_role = "read"
}

resource "github_organization_role_team" "example" {
  role_id   = github_organization_role.example.role_id
  team_slug = "example"
}

```

### Steps to Reproduce

_No response_

### Debug Output

```shell

```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deiga**
Resolves #3009
Resolves #3004

----

### Before the change?

* `role_id` wouldn't not be set during `apply`, only on next `plan`, thus rendering the resource unusable for references

### After the change?

* `role_id` is set in Create allowing it to be used in references

### Pull request checklist
- [ ] ~Schema migrations have been created if needed ([example](https://github.com/integrations/terraform-provider-github/pull/2820/files))~
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

File: github/resource_github_organization_role_test.go [hunk 1]
```diff
@@ -12,6 +12,7 @@ func TestAccGithubOrganizationRole(t *testing.T) {
 	t.Run("can create an empty organization role", func(t *testing.T) {
 		randomID := acctest.RandStringFromCharSet(5, acctest.CharSetAlphaNum)
 		name := fmt.Sprintf("tf-acc-org-role-%s", randomID)
+		baseRole := "none"
```
Comment (stevehipwell) [inline github/resource_github_organization_role_test.go]: This test is testing the optional base role defaulting to none, so this change breaks the test.

File: github/resource_github_organization_role_test.go [hunk 2]
```diff
@@ -25,12 +26,12 @@ func TestAccGithubOrganizationRole(t *testing.T) {
...
 					Config: config,
-					Check: resource.ComposeTestCheckFunc(
+					Check: resource.ComposeAggregateTestCheckFunc(
 						resource.TestCheckResourceAttrSet("github_organization_role.test", "id"),
 						resource.TestCheckResourceAttrSet("github_organization_role.test", "role_id"),
 						resource.TestCheckResourceAttr("github_organization_role.test", "name", name),
-						resource.TestCheckResourceAttr("github_organization_role.test", "base_role", "none"),
-						resource.TestCheckResourceAttrSet("github_organization_role.test", "permissions.#"),
+						resource.TestCheckResourceAttr("github_organization_role.test", "base_role", baseRole),
+						resource.TestCheckNoResourceAttr("github_organization_role.test", "permissions"),
```
Comment (stevehipwell) [inline github/resource_github_organization_role_test.go:33]: Permissions should be an empty list.

File: github/resource_github_organization_role.go [hunk 3]
```diff
@@ -73,17 +73,26 @@ func resourceGithubOrganizationRoleCreate(ctx context.Context, d *schema.Resourc
...
 		Description: github.String(d.Get("description").(string)),
-		BaseRole:    github.String(d.Get("base_role").(string)),
 		Permissions: permissionsStr,
-	})
+	}
+
+	baseRole := d.Get("base_role").(string)
+	if baseRole != "none" {
+		createOrUpdateOrgRoleOptions.BaseRole = github.String(baseRole)
+	}
```
Comment (stevehipwell) [inline github/resource_github_organization_role.go:85]: This doesn't match the API docs.

**Review by stevehipwell — CHANGES_REQUESTED** [review]
The part of this PR fixing the role ID looks good, but I'm not sure about the other changes.

According to the [API docs](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/organization-roles?apiVersion=2022-11-28#create-a-custom-organization-role) the base role should be set to `"none"`. This is the fix applied in #2968 which this PR appears to be undoing?

File: github/resource_github_organization_role_test.go (hunk 2 above)
Comment (deiga) [reply github/resource_github_organization_role_test.go:33]: I ran the tests on GHEC, the check kept failing until I changed it to this

**Comment by deiga** [comment]
> The part of this PR fixing the role ID looks good, but I'm not sure about the other changes.
> 
> According to the [API docs](https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/organization-roles?apiVersion=2022-11-28#create-a-custom-organization-role) the base role should be set to `"none"`. This is the fix applied in #2968 which this PR appears to be undoing?

Yeah, I see those docs, but running the tests on GHEC gives me a 422 Validation error if I'm passing in `"none"`.

When running a manual curl with `base_role: "none"` I get this response:
```json
{
	"message": "Invalid request.\n\nInvalid property /base_role: `none` is not a possible value. Must be one of the following: read, triage, write, maintain, admin.",
	"documentation_url": "https://docs.github.com/rest/orgs/organization-roles#create-a-custom-organization-role",
	"status": "422"
}
```

File: github/resource_github_organization_role.go (hunk 3 above)
Comment (deiga) [reply github/resource_github_organization_role.go:85]: It doesn't, but it matches API behaviour on GHEC. https://github.com/integrations/terraform-provider-github/pull/3011#issuecomment-3675455499

File: github/resource_github_organization_role_test.go (hunk 1 above)
Comment (deiga) [reply github/resource_github_organization_role_test.go]: This change doesn't modify the value of `base_role` in the resource, just the expected output. I did this, when I chose to do some modifications to the defaults of `base_role`.

But then I decided against doing changes to the resource API and this change was left in as harmless. I'll revert it, since it has no real function any more

File: github/resource_github_organization_role_test.go (hunk 2 above)
Comment (stevehipwell) [reply github/resource_github_organization_role_test.go:33]: I think you're right.

**Review by stevehipwell — APPROVED** [review]
LGTM

**Review by nickfloyd — APPROVED** [review]
