### PR TITLE
fix: change `fork` to `TypeString` and add conditional ForceNew

### LINKED ISSUE #2954: [BUG]: Pre-existing fork repositories are recreated when `fork` set to true
### Expected Behavior

The `fork` parameter can be set to true to track the forked status of pre-existing `github_repository` resources that manage fork repositories, or left blank to prevent terraform from recreating the repository.

### Actual Behavior

Terraform tries to recreate pre-existing `github_repository` resources that manage fork repositories on newer versions of the provider when the `fork` parameter is set to true.

### Terraform Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/integrations/github v6.8.3

### Affected Resource(s)

github_repository

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.5.7"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "6.8.3"
    }
  }
}

provider "github" {
  owner = "owner-here"
}

resource "github_repository" "repository" {
  name                        = "fork-bug-terraform-provider-github"
  allow_update_branch         = false
  auto_init                   = false
  description                 = "Repository forked to troubleshoot provider issue when reading repository properties"
  has_discussions             = false
  has_downloads               = true
  has_issues                  = false
  has_projects                = true
  has_wiki                    = false
  homepage_url                = "https://www.terraform.io/docs/providers/github/"

  
  # Added after upgrading to v6.8.3 from 6.7.5
  fork                   = true
  source_repo            = "terraform-provider-github"
  source_owner           = "integrations"
}
```

### Steps to Reproduce

- Manually fork a repository using the Github Web UI
- Import the repository to a `github_repository` in a terraform-provider-github version previous to #2678 (6.7.5 was used in this case)
- Run a successful apply that imports the resource, then upgrade to terraform-provider-github version 6.8.3
- Set the resource `fork`, `source_owner` and `source_repo` parameters accordingly, then run `terraform plan`

### Debug Output

```shell
Terraform will perform the following actions:                                                                                  

  # github_repository.repository must be replaced
-/+ resource "github_repository" "repository" {
      ~ default_branch              = "main" -> (known after apply)
      ~ etag                        = "W/\"...\"" -> (known after apply)
      + fork                        = true # forces replacement
      ~ full_name                   = "owner-here/fork-bug-terraform-provider-github" -> (known after apply)
      ~ git_clone_url               = "git://github.com/owner-here/fork-bug-terraform-provider-github.git" -> (known after apply)
      ~ html_url                    = "https://github.com/owner-here/fork-bug-terraform-provider-github" -> (known after apply) 
      ~ http_clone_url              = "https://github.com/owner-here/fork-bug-terraform-provider-github.git" -> (known after apply)
      ~ id                          = "fork-bug-terraform-provider-github" -> (known after apply)
      - is_template                 = false -> null
        name                        = "fork-bug-terraform-provider-github"
      ~ node_id                     = "..." -> (known after apply)
      ~ primary_language            = "Go" -> (known after apply)
      ~ private                     = false -> (known after apply)
      ~ repo_id                     = ... -> (known after apply)
      + source_owner                = "integrations" # forces replacement
      + source_repo                 = "terraform-provider-github" # forces replacement
      ~ ssh_clone_url               = "git@github.com:owner-here/fork-bug-terraform-provider-github.git" -> (known after apply) 
      ~ svn_url                     = "https://github.com/owner-here/fork-bug-terraform-provider-github" -> (known after apply) 
      ~ topics                      = [] -> (known after apply)
      ~ visibility                  = "public" -> (known after apply)
      ~ vulnerability_alerts        = false -> (known after apply)
        # (20 unchanged attributes hidden)

      - security_and_analysis {
          - secret_scanning {
              - status = "enabled" -> null
            }
          - secret_scanning_push_protection {
              - status = "enabled" -> null
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by diofeher**
Resolves #2954

----

### Before the change?

* Previously, resources tracked on the state before https://github.com/integrations/terraform-provider-github/pull/2678, didn't have the `fork` field. Now that we're supporting that, any resource that adds the attribute triggers recreation, even if the attribute is the same as the one returned by the API.

### After the change?

* We're adding `Computed` to the field, so the resource has access to the value to calculate if it needs to recreate the resource. By using that in `fork`, the other two attributes are filled in.

### Pull request checklist
- [x] Schema migrations have been created if needed ([example](https://github.com/integrations/terraform-provider-github/pull/2820/files))
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by diofeher** [comment]
I wasn't able to find a way to automate the test as I was doing it manually. It would be helpful to have another round of testing, though.

**Comment by deiga** [comment]
I think we might need to do the same to the `source_owner` and `source_repo` fields too

**Comment by diofeher** [comment]
@deiga Thanks for the catch! I previously added to them but removed them in later iterations.

So just using the `Computed` field is enough, since the read call is populating these two fields, at least that's what I've seen with my latest tests.

**Comment by diofeher** [comment]
I tested migrating from the existing field "TypeBool" to "TypeString," and it also worked well.

File: github/resource_github_repository.go [hunk 1]
```diff
@@ -479,8 +484,24 @@ func resourceGithubRepository() *schema.Resource {
...
 			},
 		},
-		CustomizeDiff: customDiffFunction,
+		CustomizeDiff: customdiff.All(
+			customDiffFunction,
+			customdiff.ForceNewIfChange("fork", func(ctx context.Context, oldVal, newVal, meta any) bool {
+				oldValStr := oldVal.(string)
+				newValStr := newVal.(string)
+				return oldValStr != "" && oldValStr != newValStr
+			}),
```
Comment (deiga) [inline github/resource_github_repository.go]:
```suggestion
			customdiff.ForceNewIfChange("fork", func(ctx context.Context, oldVal, newVal, meta any) bool {
				oldValStr := oldVal.(string)
				newValStr := newVal.(string)
				return oldValStr != "" && oldValStr != newValStr
			}),
			customdiff.ForceNewIfChange("source_owner", func(ctx context.Context, oldVal, newVal, meta any) bool {
				oldValStr := oldVal.(string)
				newValStr := newVal.(string)
				return oldValStr != "" && oldValStr != newValStr
			}),
			customdiff.ForceNewIfChange("source_repo", func(ctx context.Context, oldVal, newVal, meta any) bool {
				oldValStr := oldVal.(string)
				newValStr := newVal.(string)
				return oldValStr != "" && oldValStr != newValStr
			}),
```

File: github/resource_github_repository.go [hunk 2]
```diff
@@ -63,21 +64,25 @@ func resourceGithubRepository() *schema.Resource {
...
 				Optional:    true,
-				ForceNew:    true,
+				Computed:    true,
 				Description: "Set to 'true' to fork an existing repository.",
 			},
 			"source_owner": {
 				Type:        schema.TypeString,
 				Optional:    true,
+				Computed:    true,
 				ForceNew:    true,
```
Comment (deiga) [inline github/resource_github_repository.go]:
```suggestion
				Computed:    true,
```

File: github/resource_github_repository.go [hunk 3]
```diff
@@ -63,21 +64,25 @@ func resourceGithubRepository() *schema.Resource {
...
 				Description: "The owner of the source repository to fork from.",
 			},
 			"source_repo": {
 				Type:        schema.TypeString,
 				Optional:    true,
+				Computed:    true,
 				ForceNew:    true,
```
Comment (deiga) [inline github/resource_github_repository.go]:
```suggestion
				Computed:    true,
```

File: github/resource_github_repository.go (hunk 1 above)
Comment (diofeher) [reply github/resource_github_repository.go]: Ops, sorry I missed this review! I've added it in a later commit! Thanks

File: github/resource_github_repository.go (hunk 3 above)
Comment (diofeher) [reply github/resource_github_repository.go]: Ops, sorry I missed this review! I've added it in a later commit! Thanks

**Comment by diofeher** [comment]
Thanks for the reviews @deiga and @nickfloyd

File: github/resource_github_repository.go [hunk 4]
```diff
@@ -479,10 +482,32 @@ func resourceGithubRepository() *schema.Resource {
...
 
+// valueChangedButNotEmpty is a customdiff function that triggers recreation of the resource
+// if the field's value changes from a non-empty state to a different non-empty value.
+func valueChangedButNotEmpty(ctx context.Context, oldVal, newVal, meta any) bool {
+	oldValStr := oldVal.(string)
+	newValStr := newVal.(string)
+	return oldValStr != "" && oldValStr != newValStr
+}
+
+func customDiffFunction(_ context.Context, diff *schema.ResourceDiff, v any) error {
```
Comment (diofeher) [inline github/resource_github_repository.go:502]: I'm moving this function closer to where it's used so it's easier to read and navigate.
