### PR TITLE
Bugfix: tokenFromGHCLI not stripping api. from ghe.com hosts. Resolves #3188

### LINKED ISSUE #3188: [BUG]: tokenFromGHCLI fails to resolve token for GHEC (.ghe.com) hosts — causes silent fallback to unauthenticated client
### Expected Behavior

When 
```bash
gh auth login --hostname my-enterprise.ghe.com 
```
has been completed and no explicit [token] is set in the provider config, the provider should resolve the token from the gh CLI and make authenticated API requests.

### Actual Behavior

The provider passes api.my-enterprise.ghe.com (with api. prefix) to `gh auth token --hostname`, which doesn't match how gh stores GHEC credentials (my-enterprise.ghe.com). The lookup fails silently, the provider falls back to an unauthenticated client, and all API calls return:

Debug logs confirm unauthenticated requests (X-Ratelimit-Limit=60 instead of 5,000+).

### Terraform Version

OpenTofu v1.11.4
on linux_amd64
+ provider registry.opentofu.org/integrations/github v6.11.1

### Affected Resource(s)

All resources and data sources — the issue is in provider-level authentication, not resource-specific logic. 

Reproduced with:
github_repository

### Terraform Configuration Files

```hcl
provider "github" {
  owner    = "my-org"
  base_url = "https://api.my-enterprise.ghe.com/"
  # no token set — relying on gh CLI fallback
}

resource "github_repository" "repos" {
  for_each = toset(["my-repo"])
  name     = each.key
}
```

### Steps to Reproduce

Authenticate with gh:
```bash
gh auth login --hostname my-enterprise.ghe.com
```
1) Configure the provider with a GHEC base_url and no explicit [token]
2) Run `terraform plan` or `tofu plan`
3) All API calls fail with `401 Must authenticate to access this API.`

### Debug Output

```shell

```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by clawster**
Bugfix: tokenFromGHCLI not stripping api. from ghe.com hosts. Resolves #3188

----

### Before the change?

- `tokenFromGHCLI` only mapped `api.github.com` -> `github.com` before calling `gh auth token --hostname`
- For GHEC hosts (`api.<slug>.ghe.com`), the `api.` prefix was not stripped, causing the CLI lookup to fail silently
- The provider fell back to an unauthenticated client, resulting in 401 errors on all API calls

### After the change?

- Extended hostname mapping to strip the `api.` prefix for GHEC hosts using the existing `GHECAPIHostMatch` regex
- The provider now correctly resolves credentials from `gh` CLI for GHEC (`*.ghe.com`) instances
- Authenticated API calls now succeed when `gh auth login --hostname my-enterprise.ghe.com` has been completed

### Pull request checklist

- [ ] Schema migrations have been created if needed ([example](https://github.com/F-Secure-web/terraform-provider-github/blob/main/github/migrate_github_actions_organization_secret.go))
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

----

- **fix: resolve gh CLI token lookup for GHEC (.ghe.com) hosts**
- **Add test cases**

### CODE REVIEW

**Comment by clawster** [comment]
Replaces PR#3189 (no changes, new fork)

File: github/provider_test.go [hunk 1]
```diff
@@ -259,3 +262,65 @@ data "github_ip_ranges" "test" {}
...
+
+			// tokenFromGHCLI returns the trimmed output of the fake script,
+			// which is the hostname argument passed to `gh auth token --hostname`.
+			got := tokenFromGHCLI(u)
+			if got != tc.expectedHost {
+				t.Errorf("tokenFromGHCLI(%q): hostname passed to gh CLI = %q, want %q", tc.url, got, tc.expectedHost)
+			}
+		})
+	}
+}
```
Comment (stevehipwell) [inline github/provider_test.go]: Could you please fix the line ending?

File: github/provider_test.go [hunk 2]
```diff
@@ -259,3 +262,65 @@ data "github_ip_ranges" "test" {}
 		})
 	})
 }
+
+func Test_tokenFromGHCLI(t *testing.T) {
```
Comment (stevehipwell) [inline github/provider_test.go]: This test isn't actually testing the `tokenFromGHCLI` function as is OS specific.

File: github/provider.go [hunk 3]
```diff
@@ -506,6 +506,8 @@ func tokenFromGHCLI(u *url.URL) string {
 	host := u.Host
 	if host == DotComAPIHost {
 		host = DotComHost
+	} else if GHECAPIHostMatch.MatchString(host) {
+		host = strings.TrimPrefix(host, "api.")
 	}
```
Comment (stevehipwell) [inline github/provider.go]: If you extract this into a seperate function you can easily unit test it without having to make a fake CLI.

Comment (clawster) [reply github/provider.go]: thanks for the feedback and suggestions, that will simplify things a lot. code updated

**Comment by clawster** [comment]
Thanks for the review and suggestions, code updated

File: github/provider.go (hunk 3 above)
Comment (clawster) [reply github/provider.go]: done

**Comment by stevehipwell** [comment]
@clawster could you please rebase?

**Comment by stevehipwell** [comment]
@clawster could you please rebase so we can get this merged?
