### PR TITLE
fix: Prevent enterprise org taint on SAML enforcement error

### LINKED ISSUE #1914: [BUG]: Approving PAT taints github_enterprise_organization
### Expected Behavior

When using `github_enterprise_organization`, the permissions should work on first apply and not taint the resource when giving permissions.

### Actual Behavior

Creating a github org with `github_enterprise_organization` fails after creation because of PAT permissions:

```
│ Error: PATCH https://api.github.com/orgs/example: 403 Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization. []
│ 
│   with github_enterprise_organization.default["example"],
```

When approving access for the PAT, the resource becomes tained.

```
  # github_enterprise_organization.default["example"] is tainted, so must be replaced
-/+ resource "github_enterprise_organization" "default" {
      + description   = "Example"
      ~ id            = "O_XXX" -> (known after apply)
        name          = "example"
```

### Terraform Version

```
% terraform -version
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/integrations/github v5.37.0
```

### Affected Resource(s)

- github_enterprise_organization

### Terraform Configuration Files

_No response_

### Steps to Reproduce

```
% terraform apply
```

### Debug Output

_No response_

### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ericpardee**
Resolves #1914

----

### Before the change?

When creating a `github_enterprise_organization` in an EMU environment, REST API calls fail with SAML enforcement errors until the PAT is authorized for the new org. This affects setting `description`/`display_name` during create (and any subsequent updates). The error caused Terraform to taint the resource, leading to destroy+recreate on the next apply.

### After the change?

SAML enforcement errors during create/update are now caught and handled gracefully:
- On create: clears `description`/`display_name` from state so it reflects reality
- On update: resets fields to previous values so state stays accurate
- Returns success instead of error to prevent tainting
- Logs a warning instructing the user to authorize the PAT and re-apply

Next plan will show drift and retry after PAT authorization.

### Pull request checklist
- [ ] Schema migrations have been created if needed ([example](https://github.com/integrations/terraform-provider-github/pull/2820/files))
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ericpardee** [comment]
Tested manually in EMU environment:
- `terraform apply` → org created, SAML error on description/display_name
- Verified org not tainted, state cleared
- Authorized PAT
- `terraform plan` → no taint, shows drift for description/display_name
- `terraform apply` → fields set successfully

File: github/resource_github_enterprise_organization_test.go [hunk 1]
```diff
@@ -1,15 +1,75 @@
...
 
 import (
+	"errors"
 	"fmt"
+	"net/http"
 	"regexp"
 	"strings"
 	"testing"
 
+	"github.com/google/go-github/v67/github"
```
Comment (nickfloyd) [inline github/resource_github_enterprise_organization_test.go]:
```suggestion
	"github.com/google/go-github/v81/github"
```

File: github/resource_github_enterprise_organization.go [hunk 2]
```diff
@@ -318,10 +349,18 @@ func updateDisplayName(ctx context.Context, data *schema.ResourceData, v4 *githu
 			ctx,
 			orgName,
 			&github.Organization{
-				Name: github.Ptr(data.Get("display_name").(string)),
+				Name: github.String(newDisplayName),
```
Comment (nickfloyd) [inline github/resource_github_enterprise_organization.go]:
```suggestion
				Name: github.Ptr(newDisplayName),
```

File: github/resource_github_enterprise_organization.go [hunk 3]
```diff
@@ -301,10 +324,18 @@ func updateDescription(ctx context.Context, data *schema.ResourceData, v3 *githu
 			ctx,
 			orgName,
 			&github.Organization{
-				Description: github.Ptr(data.Get("description").(string)),
+				Description: github.String(newDesc),
```
Comment (nickfloyd) [inline github/resource_github_enterprise_organization.go]:
```suggestion
				Description: github.Ptr(newDesc),
```

**Review by nickfloyd — CHANGES_REQUESTED** [review]
Just a couple more - post merge.

**Comment by stevehipwell** [comment]
@ericpardee could you please rebase this PR?

**Comment by stevehipwell** [comment]
@nickfloyd could you please review this?
