### PR TITLE
fix: only set web_commit_signoff_required if explicitly configured

### LINKED ISSUE #2077: [BUG]: 5.43 upgrade failing due to signoff issues
### Expected Behavior

Just got the 5.43 upgrade and I'm seeing failures like: 

```
Error: PATCH https://api.github.com/repos/***: 422 Commit signoff is enforced by the organization and cannot be disabled []
```

I assume this is somehow due to https://github.com/integrations/terraform-provider-github/pull/2007/files. I've tried manually adding `web_commit_signoff_required` but this still seems to fail:

```
 # module.***.github_repository.repo will be updated in-place
  ~ resource "github_repository" "repo" {
      + web_commit_signoff_required = true
        # (35 unchanged attributes hidden)
    }
```

Is this related to something else or is there something else I should be doing here? Thank you.

### Actual Behavior

Doesn't fail / backwards compatible. 

### Terraform Version

1.2.6, 5.43

### Affected Resource(s)

- github_repository (I think)

### Terraform Configuration Files

_No response_

### Steps to Reproduce

_No response_

### Debug Output

_No response_

### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by steveteuber**
Resolves #2077

----

### Before the change?

The GitHub API 2022-11-28 version has a bug that causes a 422 error when updating a repository within an organization that has "Require sign off on web-based commits" enabled. This is because the API does not allow the `web_commit_signoff_required` field to be sent in the update request when the organization has this setting enabled.

### After the change?

The user has to explicitly set the `web_commit_signoff_required` field in the repository configuration to enable or disable it. If the field is not set in the configuration, it will not be sent in the update request, which avoids the 422 error when an organization has "Require sign off on web-based commits" enabled.

### Pull request checklist

- [ ] Schema migrations have been created if needed ([example](https://github.com/F-Secure-web/terraform-provider-github/blob/main/github/migrate_github_actions_organization_secret.go))
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by deiga** [comment]
Please rebase 😬

File: github/resource_github_repository.go [hunk 1]
```diff
@@ -638,6 +636,13 @@ func resourceGithubRepositoryObject(d *schema.ResourceData) *github.Repository {
 		}
 	}
 
+	// only configure web commit signoff if explicitly set in the configuration
+	if webCommitSignoffRequired, ok := d.GetOkExists("web_commit_signoff_required"); ok { //nolint:staticcheck,SA1019 // We sometimes need to use GetOkExists for booleans
+		if val, ok := webCommitSignoffRequired.(bool); ok {
```
Comment (stevehipwell) [inline github/resource_github_repository.go]: This code isn't doing what you think it is, `ok` is always going to be `true`.

**Comment by steveteuber** [comment]
@stevehipwell Done 😉

File: github/resource_github_repository_test.go [hunk 2]
```diff
@@ -1318,6 +1318,37 @@ resource "github_repository" "test" {
 		})
 	})
 
+	t.Run("creates repos with explicit web commit signoff required", func(t *testing.T) {
```
Comment (stevehipwell) [inline github/resource_github_repository_test.go]: Could you also add a tests to check that repos can be created with this enabled and if the field isn't set that it doesn't get populated on create and update? There should be similar tests for forking.

File: github/resource_github_repository_test.go [hunk 3]
```diff
@@ -1318,6 +1318,67 @@ resource "github_repository" "test" {
...
+					Check: resource.ComposeTestCheckFunc(
+						resource.TestCheckResourceAttr("github_repository.test", "web_commit_signoff_required", "true"),
+					),
+				},
+			},
+		})
+	})
+
+	t.Run("check_web_commit_signoff_required_not_set", func(t *testing.T) {
+		t.Skip("This test should be run manually after confirming that the test organization has been correctly configured to disable setting sign off on web-based commits at the repo level.")
```
Comment (stevehipwell) [inline github/resource_github_repository_test.go]: @steveteuber did you run this test against an org with this setting configured?

Comment (steveteuber) [reply github/resource_github_repository_test.go]: No sorry, I just have access to an org with this setting enabled...

Comment (stevehipwell) [reply github/resource_github_repository_test.go]: @steveteuber isn't that what's required for this test? I'm happy that an org without it enabled will work fine.

Comment (steveteuber) [reply github/resource_github_repository_test.go]: You're absolutely right 😅 I'll take a look at it tomorrow.

Comment (steveteuber) [reply github/resource_github_repository_test.go]: Now it's working as expected:

```shell
$ make testacc T=TestAccGithubRepository\$$/^check_web_commit_signoff_required_not_set\$$
==> Running acceptance tests on branch: 🌿 explicit_web_commit_signoff_required 🌿...
TF_ACC=1 CGO_ENABLED=0 go test ./github/... -v -run '^TestAcc' -run='TestAccGithubRepository$/^check_web_commit_signoff_required_not_set$'  -timeout 120m -count=1
=== RUN   TestAccGithubRepository
=== RUN   TestAccGithubRepository/check_web_commit_signoff_required_not_set
--- PASS: TestAccGithubRepository (16.09s)
    --- PASS: TestAccGithubRepository/check_web_commit_signoff_required_not_set (16.09s)
PASS
ok      github.com/integrations/terraform-provider-github/v6/github     16.845s
```

**Comment by stevehipwell** [comment]
@steveteuber could you please rebase this PR?

**Comment by steveteuber** [comment]
@stevehipwell Done :wink:

File: github/resource_github_repository_test.go [hunk 4]
```diff
@@ -1260,6 +1260,68 @@ resource "github_repository" "test" {
 		})
 	})
 
+	t.Run("creates repos with explicit web commit signoff required", func(t *testing.T) {
```
Comment (stevehipwell) [inline github/resource_github_repository_test.go]: Could you please split this test up into 3 tests for the 3 states; set true, set false and unset.

File: github/resource_github_repository_test.go [hunk 5]
```diff
@@ -1260,6 +1260,68 @@ resource "github_repository" "test" {
...
+		`
+
+		resource.Test(t, resource.TestCase{
+			PreCheck:          func() { skipUnauthenticated(t) },
+			ProviderFactories: providerFactories,
+			Steps: []resource.TestStep{
+				{
+					Config: fmt.Sprintf(config, testRepoName, "foo"),
+					Check: resource.ComposeTestCheckFunc(
+						resource.TestCheckResourceAttr("github_repository.test", "web_commit_signoff_required", "true"),
```
Comment (stevehipwell) [inline github/resource_github_repository_test.go:1358]: Just checking that this is the correct value for this test? If it depends on the org setting that would want to be in the skip comment.

**Comment by steveteuber** [comment]
@stevehipwell Not easy to make you happy 😄 I’ve pushed another commit of improvements.

**Comment by stevehipwell** [comment]
@steveteuber if you can rebase I'll get this merged.
