### PR TITLE
[BUG] ensure failed membership invite can be deleted

### LINKED ISSUE #2693: [BUG]: Destroy of github_membership fails if the invitation in failed state
### Expected Behavior

By documentation, destroy of github_membership should cancel the invitation or remove the user.  This should included Failed Invitations as well.  

### Actual Behavior

Destroy of github_membership only cancels active invitations.  Destroy on a github_membership in a state of failed invitation causes Github API 404 and failure of apply.

Terraform will perform the following actions:

  # github_membership.all_org_members["testuser"] will be destroyed
  # (because key ["testuser"] is not in for_each map)
  - resource "github_membership" "all_org_members" {
      - downgrade_on_destroy = false -> null
      - etag                 = "W/\"74a1af95e5838e42b9d9cb2fd68ac6sdfsdf52cfc89b36179358c986c29614ab6\"" -> null
      - id                   = "repo:testuser" -> null
      - role                 = "member" -> null
      - username             = "testuser" -> null
    }

  # github_team_membership.all_org_members["testuser"] will be destroyed
  # (because key ["testuser"] is not in for_each map)
  - resource "github_team_membership" "all_org_members" {
      - etag     = "W/\"b5e8cb74d2ac42b00decd0dsdfsdf6124eac975bdf1562308f720c4716c377004\"" -> null
      - id       = "13037747:testuser" -> null
      - role     = "member" -> null
      - team_id  = "13037747" -> null
      - username = "testuser" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.
github_team_membership.all_org_members["testuser"]: Destroying... [id=13037747:testuser]
github_team_membership.all_org_members["testuser"]: Destruction complete after 1s
github_membership.all_org_members["testuser"]: Destroying... [id=repo:testuser]
╷
│ Error: DELETE https://api.github.com/orgs/repo/memberships/testuser: 404 Cannot find testuser []
│ 
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Terraform Version

- Installed integrations/github v6.6.0 (signed by a HashiCorp partner, key ID 38027F80D7FD5FB2)

### Affected Resource(s)

- github_membership

### Terraform Configuration Files

```hcl

```

### Steps to Reproduce

_No response_

### Debug Output

```shell

```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deiga**
Supersedes #3037

Resolves #2693

----

### Before the change?

* Deleting `github_membership` when the invite had failed/expired would throw an error

### After the change?

* Deleting `github_membership` when the invite had failed/expired will ignore the 404 and complete
  * I wasn't able to write a test case which fails with the original behaviour :/

### Pull request checklist
- [ ] ~Schema migrations have been created if needed ([example](https://github.com/integrations/terraform-provider-github/pull/2820/files))~
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

File: github/resource_github_membership.go [hunk 1]
```diff
@@ -73,28 +74,28 @@ func resourceGithubMembershipCreateOrUpdate(d *schema.ResourceData, meta any) er
...
 	)
 	if err != nil {
-		return err
+		return diag.FromErr(err)
 	}
 
 	d.SetId(buildTwoPartID(orgName, username))
 
-	return resourceGithubMembershipRead(d, meta)
+	return resourceGithubMembershipRead(ctx, d, meta)
```
Comment (stevehipwell) [inline github/resource_github_membership.go]:
```suggestion
  if err = d.Set("etag", resp.Header.Get("ETag")); err != nil {
		return diag.FromErr(err)
	}
	
	return nil
```

We don't need to hit the API again.

**Review by stevehipwell — CHANGES_REQUESTED** [review]

**Review by stevehipwell — APPROVED** [review]
LGTM

**Review by nickfloyd — APPROVED** [review]
