### PR TITLE
fix: support team slug in github_team_membership

### LINKED ISSUE #1749: [BUG]: Validation error in github_team_membership when using team slug
### Describe the need

Hello, I'm duplicating the issue #1583, as it sadly seems not to be fixed for the `github_team_membership` resource.

PR #1664 only fixed this for the `github_team` and `github_team_members` resources; same fix (removing validation and allowing slugs) should probably be applied for `github_team_membership`.

Thank you 🙂 

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

```shell
Inappropriate value for attribute "team_id": string required.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kristian-lesko**
Resolves #1749.

----

### Before the change?

The `github_team_membership` would only accept numeric ID as `team_id`,
despite the docs claiming to accept a team slug as well.

### After the change?

Both numeric ID and team slug are accepted by the `team_id` field.

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

File: github/resource_github_team_membership_test.go [hunk 1]
```diff
@@ -227,6 +237,12 @@ resource "github_team_membership" "test_team_membership" {
   username = "%s"
   role     = "%s"
 }
+
+resource "github_team_membership" "test_team_membership_slug" {
+  team_id  = "${github_team.test_team.slug}"
+  username = "%s"
+  role     = "%s"
+}
 `, username, randString, username, role)
```
Comment (kfcampbell) [inline github/resource_github_team_membership_test.go:246]: Looks like we'll need another argument here on line 246 so that the team slug can be inserted into the above string!

**Review by kfcampbell — APPROVED** [review]
Thank you!
