### PR TITLE
[MAINT] Fixup `github_repository_file`

### LINKED ISSUE #3161: [BUG]: Unable to import a github_repository_file from default branch with provider 6.11.0
### Expected Behavior

Running the following, should import a file from the default branch:
```
terraform import 'github_repository_file.this' <REPO>/<FILE_PATH>
```

### Actual Behavior

Returns the follwing:
```
Error: invalid ID specified. Supplied ID must be written as <repository>/<file path>:<branch>. unexpected ID format ("<REPO>/<FILE_PATH>"); expected 2 parts separated by ":"
```

### Terraform Version

Terraform v1.14.4
on linux_amd64
+ provider registry.terraform.io/integrations/github v6.11.0

### Affected Resource(s)

- github-repository-file

### Terraform Configuration Files

```hcl
resource "github_repository_file" "this" {
  repository = <REPO>
  file       = <FILE_PATH>
  content = ""
  commit_message      = "chore: update file"
  overwrite_on_create = true
}
```

### Steps to Reproduce

```
terraform import 'github_repository_file.this' <REPO>/<FILE_PATH>
```

### Debug Output

```shell

```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deiga**
Resolves #3161

----

### Before the change?

- There was no test for importing `github_repository_file`
- Import format: repo/file or repo/file:branch; default branch was imported without an explicit branch segment.
- Branch field: branch was optional and not Computed; state could omit it for default-branch resources.
- State: No migration for old ID formats; repository_id was not part of the resource’s state.
- autocreate_branch: Used in Read, Update, and Delete; no deprecation notice.

### After the change?

- We have tests for importing `github_repository_file`
- Adds Computed: true to `branch`
- Adds computed `repository_id` field and enables repo renaming without resource recreation
- Computes `branch` on create or import if not specified
- Changes ID schema from `<repo>/<file>` to `<repo>:<file>:<branch>` to enable safer usage of multiple files from same repo but different branches
- Adds State migration for computing `branch`, `repository_id` and new `ID` format
- Import format: repo:file:branch (colon-separated); default branch uses repo:file: (trailing colon). Matches the internal ID format.
- autocreate_branch: Deprecated and no longer used in Read, Update, or Delete.

### Pull request checklist

- [x] Schema migrations have been created if needed ([example](https://github.com/F-Secure-web/terraform-provider-github/blob/main/github/migrate_github_actions_organization_secret.go))
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by deiga** [comment]
image

File: github/resource_github_repository_file.go [hunk 1]
```diff
@@ -436,10 +436,20 @@ func resourceGithubRepositoryFileImport(ctx context.Context, d *schema.ResourceD
 	owner := meta.(*Owner).name
 	repo, file := splitRepoFilePath(repoFilePath)
 
-	opts := &github.RepositoryContentGetOptions{Ref: branch}
-	if err := d.Set("branch", branch); err != nil {
+	repoInfo, _, err := client.Repositories.Get(ctx, owner, repo)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go:446]: Why do we need to know if the branch is the default if it's been passed in?

**Review by nickfloyd — DISMISSED** [review]

**Review by stevehipwell — CHANGES_REQUESTED** [review]
I missed the fact that the branch is optional, I think this should be required in the next major version. As it's optional then the import ID should allow it to be not set.

**Comment by stevehipwell** [comment]
So what I'm saying is the following changes are needed to fix this resource.

- Add `Computed: true` to `branch`
- Compute branch on create if not specified
- Support importing with ID missing branch (compute on import only if missing)
- Add migration to fix defect with ID not containing branch and missing `branch` computed value

File: github/resource_github_repository_file.go [hunk 2]
```diff
@@ -215,7 +234,9 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 		return diag.FromErr(err)
 	}
 
-	d.SetId(fmt.Sprintf("%s/%s", repo, file))
+	branch := d.Get("branch").(string)
+
+	d.SetId(fmt.Sprintf("%s/%s:%s", repo, file, branch))
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: This should use `buildID()`.

File: github/resource_github_repository_file.go [hunk 3]
```diff
@@ -427,27 +448,34 @@ func autoBranchDiffSuppressFunc(k, _, _ string, d *schema.ResourceData) bool {
 }
 
 func resourceGithubRepositoryFileImport(ctx context.Context, d *schema.ResourceData, meta any) ([]*schema.ResourceData, error) {
-	repoFilePath, branch, err := parseID2(d.Id())
-	if err != nil {
-		return nil, fmt.Errorf("invalid ID specified. Supplied ID must be written as <repository>/<file path>:<branch>. %w", err)
+	importIDParts := strings.Split(d.Id(), idSeparator)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: This should use `parseID2()` and the ID spec should be `<repo>/<file>:` for the default branch.

**Comment by deiga** [comment]
@stevehipwell Done. But I wonder if I should just refactor the import ID now as well? Sure, it's technically a breaking change, but imports are "one-off" usually

**Comment by stevehipwell** [comment]
> @stevehipwell Done. But I wonder if I should just refactor the import ID now as well? Sure, it's technically a breaking change, but imports are "one-off" usually

@deiga I think this makes sense. @nickfloyd thoughts?

We should also add `repository_id` to the schema as part of the migration, add the `diffRepository`, and remove `ForceNew` from `repository`; this will stop files being destroyed if the repo name changes.

**Comment by deiga** [comment]
@stevehipwell Addressed your comments. And re-introduced the API Mock pattern here, since it's the only way to verify the migration.

Would you still prefer that we discuss before we can add this pattern?

**Comment by stevehipwell** [comment]
> Would you still prefer that we discuss before we can add this pattern?

Yes, I don't think this is the time to add this; but I think it's something we need to explore further.

**Comment by deiga** [comment]
@stevehipwell Done

File: github/resource_github_repository_file_migration_test.go [hunk 4]
```diff
@@ -0,0 +1,155 @@
+// TODO: Enable this test once we have a way to mock the GitHub API
+
+// package github
```
Comment (stevehipwell) [inline github/resource_github_repository_file_migration_test.go]:
```suggestion
package github

// TODO: Enable this test once we have a way to mock the GitHub API
```

File: github/resource_github_repository_file.go [hunk 5]
```diff
@@ -161,6 +176,8 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 
 	checkOpt := github.RepositoryContentGetOptions{}
 
+	repoInfo, _, err := client.Repositories.Get(ctx, owner, repo)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go:181]: This is missing an error handler.

File: github/resource_github_repository_file.go [hunk 6]
```diff
@@ -175,6 +192,17 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 			}
 		}
 		checkOpt.Ref = branch.(string)
+	} else {
+		if err != nil {
+			return diag.FromErr(err)
+		}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: I think this is the missing error handler from above?

File: github/resource_github_repository_file.go [hunk 7]
```diff
@@ -227,7 +261,11 @@ func resourceGithubRepositoryFileRead(ctx context.Context, d *schema.ResourceDat
 	client := meta.(*Owner).v3client
 	owner := meta.(*Owner).name
 
-	repo, file := splitRepoFilePath(d.Id())
+	repo, file, _, err := parseID3(d.Id())
+	if err != nil {
+		return diag.FromErr(err)
+	}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: We should use `d.Get()` instead of parsing the ID.

File: github/resource_github_repository_file.go [hunk 8]
```diff
@@ -175,6 +192,17 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 			}
 		}
 		checkOpt.Ref = branch.(string)
+	} else {
+		if err != nil {
+			return diag.FromErr(err)
+		}
+		if err := d.Set("branch", repoInfo.GetDefaultBranch()); err != nil {
+			return diag.FromErr(err)
+		}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: Why not set `branch` here and then do `d.Set()` after the file has been created successfully?

File: github/resource_github_repository_file.go [hunk 9]
```diff
@@ -215,7 +243,13 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 		return diag.FromErr(err)
 	}
 
-	d.SetId(fmt.Sprintf("%s/%s", repo, file))
+	branch := d.Get("branch").(string)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: See above.

File: github/resource_github_repository_file.go
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: The branch will always be set so this logic should be simplified.

File: github/resource_github_repository_file.go [hunk 10]
```diff
@@ -427,28 +465,50 @@ func autoBranchDiffSuppressFunc(k, _, _ string, d *schema.ResourceData) bool {
...
 
 	client := meta.(*Owner).v3client
 	owner := meta.(*Owner).name
-	repo, file := splitRepoFilePath(repoFilePath)
 
-	opts := &github.RepositoryContentGetOptions{Ref: branch}
-	if err := d.Set("branch", branch); err != nil {
+	opts := &github.RepositoryContentGetOptions{}
+
+	repoInfo, _, err := client.Repositories.Get(ctx, owner, repo)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go:446]: The error handler for this is misisng.

File: github/resource_github_repository_file.go
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: Same as above.

**Comment by deiga** [comment]
@stevehipwell 

> you'll also need to add an ID set to update as the ID needs to be updated if the repo name has changed.

Doesn't ForceNew run `Create`, so that shouldn't be needed in `Update`?

**Comment by stevehipwell** [comment]
> Doesn't ForceNew run Create, so that shouldn't be needed in Update?

The diff function supports changing the repo name without forcing new, so we have to set the ID in update.

**Comment by deiga** [comment]
@stevehipwell If the `repository_id` changes, then we set `ForceNew` on `repository`. Which triggers `Create` instead if `Update`, or do I have that mixed up? 
Is there any case where `repository_id` would change and need to be set in `Update`?

**Comment by stevehipwell** [comment]
> @stevehipwell If the repository_id changes, then we set ForceNew on repository. Which triggers Create instead if Update, or do I have that mixed up?
Is there any case where repository_id would change and need to be set in Update?

The resource ID uses repo name so we need to call `d.SetId()`, not update the `repository_id` as that is static.

File: github/resource_github_repository_file.go [hunk 11]
```diff
@@ -174,7 +196,13 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
...
 		}
-		checkOpt.Ref = branch.(string)
+		checkOpt.Ref = branch
+	} else {
+		branch = repoInfo.GetDefaultBranch()
+	}
+
+	if err := d.Set("repository_id", int(repoInfo.GetID())); err != nil {
+		return diag.FromErr(err)
 	}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: I'd move this below `d.SetId()`.

File: github/resource_github_repository_file.go [hunk 12]
```diff
@@ -215,7 +243,18 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 		return diag.FromErr(err)
 	}
 
-	d.SetId(fmt.Sprintf("%s/%s", repo, file))
+	if err := d.Set("branch", branch); err != nil {
+		return diag.FromErr(err)
+	}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: I'd move this below `d.SetId()`.

File: github/resource_github_repository_file.go [hunk 13]
```diff
@@ -227,30 +266,34 @@ func resourceGithubRepositoryFileRead(ctx context.Context, d *schema.ResourceDat
...
-	repo, file := splitRepoFilePath(d.Id())
-	ctx = tflog.SetField(ctx, "repository", repo)
+	repoName, ok := d.Get("repository").(string)
+	if !ok {
+		return diag.FromErr(fmt.Errorf("repository not found or is not a string"))
+	}
+	file, ok := d.Get("file").(string)
+	if !ok {
+		return diag.FromErr(fmt.Errorf("file not found or is not a string"))
+	}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]:
```suggestion
	repoName := d.Get("repository").(string)
	file := d.Get("file").(string)
	branch := d.Get("branch").(string
```

I don't think you need the OK check here as the types a defined in the schema and `d.Get()` returns an empty type if not found; so the outcome is always valid even if nothing is found.

Also branch should be fetched here.

File: github/resource_github_repository_file.go [hunk 14]
```diff
@@ -349,18 +387,15 @@ func resourceGithubRepositoryFileUpdate(ctx context.Context, d *schema.ResourceD
...
-		tflog.Debug(ctx, "Using explicitly set branch", map[string]any{
-			"branch": branch.(string),
-		})
-		if err := checkRepositoryBranchExists(client, owner, repo, branch.(string)); err != nil {
-			if d.Get("autocreate_branch").(bool) {
-				if err := resourceGithubRepositoryFileCreateBranch(ctx, d, meta); err != nil {
-					return diag.FromErr(err)
-				}
-			} else {
+	branch := d.Get("branch").(string)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: This should be up with repo and file.

File: github/resource_github_repository_file.go [hunk 15]
```diff
@@ -227,30 +266,34 @@ func resourceGithubRepositoryFileRead(ctx context.Context, d *schema.ResourceDat
...
-		if err := checkRepositoryBranchExists(client, owner, repo, branch.(string)); err != nil {
-			if d.Get("autocreate_branch").(bool) {
-				branch = d.Get("autocreate_branch_source_branch").(string)
-			} else {
-				tflog.Info(ctx, "Removing repository path from state because the branch no longer exists in GitHub")
-				d.SetId("")
-				return nil
-			}
+	branch := d.Get("branch").(string)
+	if err := checkRepositoryBranchExists(ctx, client, owner, repoName, branch); err != nil {
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: This looks wrong to me, read is only called after the resource is created so if the branch no longer exists it should error or have the ID set to empty.

IMHO longer term the ability for this resource to create a branch needs to be removed as it doesn't fit with the TF model, if you need a branch there is a resource for that which will follow the correct TF lifecycle.

File: github/resource_github_repository_file.go [hunk 16]
```diff
@@ -227,30 +266,34 @@ func resourceGithubRepositoryFileRead(ctx context.Context, d *schema.ResourceDat
...
+		if d.Get("autocreate_branch").(bool) {
+			branch = d.Get("autocreate_branch_source_branch").(string)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: OK, this is fully incorrect. Read is meant to reflect the state of the system and if the branch doesn't exist then the content is empty.

File: github/resource_github_repository_file.go [hunk 17]
```diff
@@ -427,28 +458,60 @@ func autoBranchDiffSuppressFunc(k, _, _ string, d *schema.ResourceData) bool {
...
+			return nil, err
+		}
+	} else {
+
+		defaultBranch := repoInfo.GetDefaultBranch()
+		branch = defaultBranch
+		if err := d.Set("branch", branch); err != nil {
+			return nil, err
+		}
+	}
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]:
```suggestion
	if branch == "" {
		branch = repoInfo.GetDefaultBranch()		
	}
	
	opts.Ref = branch
	
	if err := d.Set("branch", branch); err != nil {
		return nil, err
	}
```
But move the two sets down with the other sets for consistency.

**Review by stevehipwell — CHANGES_REQUESTED** [review]

**Comment by deiga** [comment]
@stevehipwell Doh! 🤦 
Sorry, I kept misunderstanding your point

**Comment by deiga** [comment]
@stevehipwell I went and deprecated the whole `autocreate_branch` stuff, let me know if I went too far :D

And, could you update the title of this PR to something like "resource_github_repository_file: fix import format and add state migrations"

File: github/resource_github_repository_file.go [hunk 18]
```diff
@@ -174,7 +199,9 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
 				return diag.FromErr(err)
 			}
 		}
-		checkOpt.Ref = branch.(string)
+		checkOpt.Ref = branch
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: Can we move this out of the if/else block so we're always being explicit about the branch? This would also be consistent with the rest of the code.

File: github/resource_github_repository_file.go [hunk 19]
```diff
@@ -215,10 +242,25 @@ func resourceGithubRepositoryFileCreate(ctx context.Context, d *schema.ResourceD
...
 		return diag.FromErr(err)
 	}
+	if err := d.Set("branch", branch); err != nil {
+		return diag.FromErr(err)
+	}
+	if err := d.Set("repository_id", int(repoInfo.GetID())); err != nil {
+		return diag.FromErr(err)
+	}
 
 	return resourceGithubRepositoryFileRead(ctx, d, meta)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go:265]: We shouldn't need this as long as all of the computed values are being set above.

File: github/resource_github_repository_file.go [hunk 20]
```diff
@@ -227,35 +269,26 @@ func resourceGithubRepositoryFileRead(ctx context.Context, d *schema.ResourceDat
...
-		}
-		opts.Ref = branch.(string)
-	}
+	opts.Ref = branch
 
-	fc, _, _, err := client.Repositories.GetContents(ctx, owner, repo, file, opts)
+	fc, _, _, err := client.Repositories.GetContents(ctx, owner, repoName, file, opts)
 	if err != nil {
 		var errorResponse *github.ErrorResponse
 		if errors.As(err, &errorResponse) && errorResponse.Response.StatusCode == http.StatusTooManyRequests {
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: Is this correct?

File: github/resource_github_repository_file.go [hunk 21]
```diff
@@ -345,31 +373,20 @@ func resourceGithubRepositoryFileUpdate(ctx context.Context, d *schema.ResourceD
...
+	ctx = tflog.SetField(ctx, "branch", branch)
 
 	opts := resourceGithubRepositoryFileOptions(d)
 
 	if *opts.Message == fmt.Sprintf("Add %s", file) {
 		opts.Message = github.Ptr(fmt.Sprintf("Update %s", file))
 	}
 
+	// TODO: Use UpdateFile if the file already exists
 	create, _, err := client.Repositories.CreateFile(ctx, owner, repo, file, opts)
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go]: Why not swap this over now? The `sha` value should be empty if the file doesn't already exist.

File: github/resource_github_repository_file.go (hunk 19 above)
Comment (deiga) [reply github/resource_github_repository_file.go:265]: I know, but I've been dreading removing it as there is so much computed stuff going in `Read` which doesn't exist in `Create`.

Honestly, it's a can of worms I'd like to keep out of this scope

File: github/resource_github_repository_file.go (hunk 20 above)
Comment (deiga) [reply github/resource_github_repository_file.go]: It was in there. I doubt it actually does anything 🤷

Comment (deiga) [reply github/resource_github_repository_file.go]: It was introduced in https://github.com/integrations/terraform-provider-github/pull/2345/changes 
Considering that it was supposed to protect from rate-limiting, I think it's no longer applicable

File: github/resource_github_repository_file.go (hunk 21 above)
Comment (deiga) [reply github/resource_github_repository_file.go]: I'm scared 😂

File: github/resource_github_repository_file.go (hunk 19 above)
Comment (stevehipwell) [reply github/resource_github_repository_file.go:265]: I don't think any of that is actually relevant after create has run, but I guess we could pick that up in a follow up PR?

File: github/resource_github_repository_file.go [hunk 22]
```diff
@@ -227,35 +269,22 @@ func resourceGithubRepositoryFileRead(ctx context.Context, d *schema.ResourceDat
...
+	opts.Ref = branch
 
-	fc, _, _, err := client.Repositories.GetContents(ctx, owner, repo, file, opts)
+	fc, _, _, err := client.Repositories.GetContents(ctx, owner, repoName, file, opts)
 	if err != nil {
-		var errorResponse *github.ErrorResponse
-		if errors.As(err, &errorResponse) && errorResponse.Response.StatusCode == http.StatusTooManyRequests {
-			return diag.FromErr(err)
-		}
+		return diag.FromErr(deleteResourceOn404AndSwallow304OtherwiseReturnError(err, d, "repository file %s/%s:%s:%s", owner, repoName, file, branch))
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go:287]: I don't think we're using etag here so do we think this is safe or would we be better to just use the inline 404 pattern?

File: github/resource_github_repository_file.go [hunk 23]
```diff
@@ -345,40 +369,36 @@ func resourceGithubRepositoryFileUpdate(ctx context.Context, d *schema.ResourceD
...
 	if err != nil {
 		return diag.FromErr(err)
 	}
 
-	if err = d.Set("commit_sha", create.GetSHA()); err != nil {
+	if err = d.Set("commit_sha", update.GetSHA()); err != nil {
 		return diag.FromErr(err)
 	}
 
+	if d.HasChanges("repository", "file", "branch") {
```
Comment (stevehipwell) [inline github/resource_github_repository_file.go:394]: Is this worth the check or are we best just setting the value? If it's worth the check we ought to use it elsewhere.

File: website/docs/r/repository_file.html.markdown [hunk 24]
```diff
@@ -57,55 +59,53 @@ resource "github_repository_file" "foo" {
...
 
-* `autocreate_branch_source_sha` - (Optional) The commit hash to start from, if 'autocreate_branch' is set. Defaults to the tip of 'autocreate_branch_source_branch'. If provided, 'autocreate_branch_source_branch' is ignored.
+- `autocreate_branch_source_sha` - (Optional) The commit hash to start from, if 'autocreate_branch' is set. Defaults to the tip of 'autocreate_branch_source_branch'. If provided, 'autocreate_branch_source_branch' is ignored.
 
 ## Attributes Reference
 
 The following additional attributes are exported:
 
-* `commit_sha` - The SHA of the commit that modified the file.
+- `commit_sha` - The SHA of the commit that modified the file.
```
Comment (stevehipwell) [inline website/docs/r/repository_file.html.markdown:93]: I think we need to add `repository_id` here?

File: github/resource_github_repository_file.go (hunk 22 above)
Comment (deiga) [reply github/resource_github_repository_file.go:287]: It looks safe to me, since it just compares status codes. The GH API doesn't return a 304 unless stuff didn't change

File: github/resource_github_repository_file.go (hunk 23 above)
Comment (deiga) [reply github/resource_github_repository_file.go:394]: Probably not _really_ worth it. But I like the thought of only doing any changes if there are changes. Especially if it's API things (which this isn't, sure)

No strong feelings on this specific change, but I think the pattern is something we should discuss adopting

**Review by nickfloyd — APPROVED** [review]
