### PR TITLE
[MAINT][FEAT] Fix Org Ruleset tests && enable `allowed_merge_methods`

### LINKED ISSUE #2530: [FEAT]: Support ruleset `allowed_merge_methods`
### Describe the need

I want to be able to specify the `allowed_merge_methods` for both repo and org rulesets. This change depends on https://github.com/google/go-github/pull/3417.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deiga**
Resolves #2530, https://github.com/integrations/terraform-provider-github/issues/2536, https://github.com/integrations/terraform-provider-github/issues/2717

----

### Before the change?

* Running `TEST="./github" TESTARGS="-run TestGithubOrganizationRulesets" make testacc` would fail due to multiple issues in the test setup

### After the change?

* Running `TEST="./github" TESTARGS="-run TestGithubOrganizationRulesets" make testacc` will show all tests as passing
* Switch from `NewSubsystemLoggingHTTPTransport` to `NewLoggingHTTPTransport` as we don't actually initialize a Subsystem anywhere, which creates spam. 
* Migrate `github/resource_github_organization_ruleset.go` and `github/resource_github_repository.go` to use Context aware CRUD methods
* Add `rules.pull_requests.allowed_merge_methods` handling to `github/resource_github_repository_ruleset.go` and `github/resource_github_organization_ruleset.go`

### Pull request checklist
- [ ] ~Schema migrations have been created if needed ([example](https://github.com/integrations/terraform-provider-github/pull/2820/files))~
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by stevehipwell** [comment]
@deiga would it be possible to hold off on this until we get #2941 merged?

**Comment by deiga** [comment]
> @deiga would it be possible to hold off on this until we get #2941 merged?

@stevehipwell Sure! Would you want to rebase that branch on top of go-github-v68, so that I could use it as a base for this PR?

**Comment by stevehipwell** [comment]
@deiga the acceptance tests PR should be compatible with the v6 releases, so the v7 branch would be rebased on it. I'm currently re-running the tests to get it ready to be merged and I'm picking up defects in the currently released code.

File: github/resource_github_organization_ruleset_test.go [hunk 1]
```diff
@@ -12,10 +12,36 @@ import (
...
+	visibility = "private"
+	auto_init = true
+	ignore_vulnerability_alerts_during_read = true
+}
+
+resource "github_repository_file" "workflow_file" {
+	repository          = github_repository.test.name
+	branch              = "main"
+	file                = "%[3]s"
+	content             = "name: Echo Workflow\n\non: [pull_request]\n\njobs:\n    echo:\n      runs-on: linux\n      steps:\n        - run: echo \"Hello, world!\"\n"
```
Comment (stevehipwell) [inline github/resource_github_organization_ruleset_test.go]:
```suggestion
	content             = <<EOT
name: Echo Workflow

on: [pull_request]

jobs:
  echo:
    runs-on: linux
    steps:
      - run: echo \"Hello, world!\"
EOT
```

File: github/resource_github_organization_ruleset_test.go [hunk 2]
```diff
@@ -79,8 +106,9 @@ resource "github_organization_ruleset" "test" {
 		required_workflows {
 			do_not_enforce_on_create = true
 			required_workflow {
-				path          = "path/to/workflow.yaml"
-				repository_id = 1234
+				path          = "%[3]s"
```
Comment (stevehipwell) [inline github/resource_github_organization_ruleset_test.go]:
```suggestion
				path          = github_repository_file.workflow_file.path
```

File: github/resource_github_organization_ruleset_test.go [hunk 3]
```diff
@@ -101,8 +129,9 @@ resource "github_organization_ruleset" "test" {
 
 		non_fast_forward = true
 	}
+	depends_on = [github_repository_file.workflow_file]
```
Comment (stevehipwell) [inline github/resource_github_organization_ruleset_test.go]:
```suggestion
```

File: github/util_rules.go [hunk 4]
```diff
@@ -1,13 +1,16 @@
...
 import (
+	"log"
 	"reflect"
 	"sort"
 
 	"github.com/google/go-github/v81/github"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
 )
 
+var DEFAULT_PULL_REQUEST_MERGE_METHODS = []github.PullRequestMergeMethod{github.PullRequestMergeMethodMerge, github.PullRequestMergeMethodRebase, github.PullRequestMergeMethodSquash}
```
Comment (stevehipwell) [inline github/util_rules.go]:
```suggestion
var defaultPullRequestMergeMethods = []github.PullRequestMergeMethod{github.PullRequestMergeMethodMerge, github.PullRequestMergeMethodRebase, github.PullRequestMergeMethodSquash}
```
Constants/vars should use idiomatic Go naming.

File: github/util_rules.go [hunk 5]
```diff
@@ -115,9 +133,15 @@ func flattenBypassActors(bypassActors []*github.BypassActor) []any {
...
-
-		actorMap["actor_id"] = v.GetActorID()
-		actorMap["actor_type"] = v.GetActorType()
+		actorID := v.GetActorID()
+		actorType := v.GetActorType()
+		if *actorType == github.BypassActorTypeOrganizationAdmin && actorID == 0 {
+			// This is a workaround for the GitHub API bug where OrganizationAdmin actor_id is returned as `null` instead of `1`
+			log.Printf("[DEBUG] Setting OrganizationAdmin Actor ID to 1")
+			actorID = 1
+		}
```
Comment (stevehipwell) [inline github/util_rules.go]: I don't agree with this, we don't actually know what the correct representation is and I personally have 1000s of instances that I've stabilized on `0`. We should be able to support both values being set without causing a drift.

File: github/util_rules.go (hunk 4 above)
Comment (stevehipwell) [reply github/util_rules.go]: FYI this is a short term fix for a SDK defect.

File: github/util_rules.go (hunk 5 above)
Comment (deiga) [reply github/util_rules.go]: Yeah. It seems that the updates to SDK and the removal of Read from Create actually stabilized the ID drift, even though the API still returns `null` incorrectly.
I'll just remove this piece and lets think of a solution if it's still being reported as a problem
