### PR TITLE
[BUG] Ensure repository creation works if vulnerability-alerts isn't modifiable on repo level

### LINKED ISSUE #2988: [BUG]: creation of github_repository fails from v6.7.0 onwards
### Expected Behavior

Applying the Terraform plan for  a new `github_repository` with `vulnerability_alerts = true` should create the repository without producing an error.

This is running in an GitHub Enterprise Cloud account.

It works fine with provider version `6.6.0` but fails with `6.7.0` to `6.9.0` (error below).

Possibly related to https://github.com/integrations/terraform-provider-github/pull/2501.

### Actual Behavior

Terraform errors, creates the repository but the state is broken with some attributes missing. Just applying Terraform again does not fix the issues.

```
 Error: DELETE https://api.github.com/repos/lessonnine/jts-test.test/vulnerability-alerts: 422 An enforced security configuration prevented modifying dependabot alerts enablement. Contact your organization owner for details. []
│ 
│   with github_repository.lessonnine-jts-test-test,
│   on generated.tf line 50028, in resource "github_repository" "lessonnine-jts-test-test":
│ 50028: resource "github_repository" "lessonnine-jts-test-test" {
```

### Terraform Version

Terraform version `1.11.4` on `linux_amd64`.

### Affected Resource(s)

- `github_repository`

### Terraform Configuration Files

```hcl
resource "github_repository" "lessonnine-jts-test-test" {
  name        = "jts-test.test"
  description = "Just for testing GitHub api (Infrastructure)"

  topics = [
    "infrastructure",
  ]

  has_issues   = false
  has_projects = true
  has_wiki     = false

  allow_rebase_merge = false
  allow_squash_merge = false

  visibility = "private"

  vulnerability_alerts = true # test adding this attribute

  auto_init              = true
  delete_branch_on_merge = true
  allow_update_branch    = true
  allow_auto_merge       = true

  lifecycle {
    prevent_destroy = true

    ignore_changes = [
      # vulnerability alerts are managed via org-wide settings
      vulnerability_alerts,
    ]
  }
}


with provider version:


    github = {
      source  = "integrations/github"
      version = "6.7.0"
    }
```

### Steps to Reproduce

```
$ terraform apply
```

### Debug Output

```shell
Error: DELETE https://api.github.com/repos/lessonnine/jts-test.test/vulnerability-alerts: 422 An enforced security configuration prevented modifying dependabot alerts enablement. Contact your organization owner for details. []
│ 
│   with github_repository.lessonnine-jts-test-test,
│   on generated.tf line 50028, in resource "github_repository" "lessonnine-jts-test-test":
│ 50028: resource "github_repository" "lessonnine-jts-test-test" {
```

### Panic Output

```shell
none
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deiga**
Resolves #2988 

----

### Before the change?

* `resource_github_repository.go` was using Context-unaware functions
* All errors in `updateVulnerabilityAlerts` would cause terraform to fail

### After the change?

* `resource_github_repository.go` is using Context-aware functions
* Ignore specific 422 response error in  `updateVulnerabilityAlerts` to ensure repo creation works if vulnerability alerts are not modifiable

### Pull request checklist
- [ ] ~Schema migrations have been created if needed ([example](https://github.com/integrations/terraform-provider-github/pull/2820/files))~
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~Docs have been reviewed and added / updated if needed (for bug fixes / features)~

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

File: github/resource_github_repository.go [hunk 1]
```diff
@@ -1243,11 +1243,17 @@ func resourceGithubParseFullName(resourceDataLike interface {
 }
 
 func updateVulnerabilityAlerts(d *schema.ResourceData, client *github.Client, ctx context.Context, owner, repoName string) error {
-	updateVulnerabilityAlerts := client.Repositories.DisableVulnerabilityAlerts
-	if vulnerabilityAlerts, ok := d.GetOk("vulnerability_alerts"); ok && vulnerabilityAlerts.(bool) {
-		updateVulnerabilityAlerts = client.Repositories.EnableVulnerabilityAlerts
+	updateVulnerabilityAlertsSDK := client.Repositories.DisableVulnerabilityAlerts
+	vulnerabilityAlerts, ok := d.GetOk("vulnerability_alerts")
+	if ok && vulnerabilityAlerts.(bool) {
```
Comment (stevehipwell) [inline github/resource_github_repository.go:1251]: Would it not be even cleaner to use a pattern more like the following?

```go
	updateVulnerabilityAlertsSDK := client.Repositories.DisableVulnerabilityAlerts
  vulnerabilityAlerts, ok := d.GetOk("vulnerability_alerts")
  
  if !ok {
    return nil
  }

	if vulnerabilityAlerts.(bool) {
		updateVulnerabilityAlertsSDK = client.Repositories.EnableVulnerabilityAlerts
	}
```

Comment (deiga) [reply github/resource_github_repository.go:1251]: Good question! Unfortunately, not. New repos will have `vulnerability_alerts` enabled by default, so they need to be disabled unless it's actually set by the user to be enabled.

Of course we could change it to behave differently, but that'd be a breaking change

Comment (deiga) [reply github/resource_github_repository.go:1251]: Maybe it could make sense to extract `vulnerability_alerts` into it's own resource in v7.x and make that breaking change there

Comment (stevehipwell) [reply github/resource_github_repository.go:1251]: > Unfortunately, not. New repos will have vulnerability_alerts enabled by default, so they need to be disabled unless it's actually set by the user to be enabled.

I don't think this is the case anymore as AFAIK this can be configured at the organization level and is the cause of this defect. Given this GitHub change the code shouldn't make any changes to the default unless explicitly specified by the user.

> Of course we could change it to behave differently, but that'd be a breaking change

IMHO this is a required change and while it could be considered breaking leaving the current behaviour isn't an option.

> Maybe it could make sense to extract vulnerability_alerts into it's own resource in v7.x and make that breaking change there

I'd say this should be part of `v6.10.0` if possible with the inline repo variable deprecated.

File: github/resource_github_repository.go [hunk 2]
```diff
@@ -1243,11 +1243,20 @@ func resourceGithubParseFullName(resourceDataLike interface {
...
+	// Only if the vulnerability alerts are specifically set to true, enable them.
+	// Otherwise, disable them as GitHub defaults to enabled and we have not wanted to introduce a breaking change for this yet.
+	if ok && vulnerabilityAlerts.(bool) {
+		updateVulnerabilityAlertsSDK = client.Repositories.EnableVulnerabilityAlerts
 	}
 
-	_, err := updateVulnerabilityAlerts(ctx, owner, repoName)
+	resp, err := updateVulnerabilityAlertsSDK(ctx, owner, repoName)
+	if err != nil {
+		if resp.StatusCode == http.StatusUnprocessableEntity && strings.Contains(err.Error(), "An enforced security configuration prevented modifying") && !ok {
```
Comment (stevehipwell) [inline github/resource_github_repository.go:1259]: This would be a brittle fix, the documented REST API is hard enough to work with so using an error message to control logic isn't something I'd be comfortable doing.

I think the current behaviour is defective given the subsequent GitHub changes. Based on my understanding of `d.GetOK()` a change like the one I suggested above would only impact new public repos where there is no organization controlled default.

**Review by stevehipwell — CHANGES_REQUESTED** [review]

File: github/resource_github_repository.go (hunk 1 above)
Comment (deiga) [reply github/resource_github_repository.go:1251]: I did try this with my own non-paid Org and without having anything configured both `private` and `public` repos had `vulnerability_alerts` by default.

I agree that we should deprecate this ASAP, as having this enabled by default makes a lot of sense

File: github/resource_github_repository.go (hunk 2 above)
Comment (deiga) [reply github/resource_github_repository.go:1259]: I did try using `d.GetOk()` and skipping Delete/Enable with a non-paid Org and private repo. That left the state in a weird state, as vulnerability_alerts was enabled by default and TF had trouble consolidating configuration vs remote state.

I agree that using the error message is problematic, but I can't see any other way to do this with our current limitations.
There are many other cases where a 422 status code shouldn't be ignored, so we can't base it on that either

File: github/resource_github_repository.go (hunk 1 above)
Comment (stevehipwell) [reply github/resource_github_repository.go:1251]: The comment in code says that this should be off by default for private repos but the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts#access-to-dependabot-alerts) suggest that this has been modified to always be on by default.

File: github/resource_github_repository.go (hunk 2 above)
Comment (stevehipwell) [reply github/resource_github_repository.go:1259]: Actually there isn't a good solution for this, even with my pattern the API will be hit every time there is an unrelated repo change. I guess we could remove computed and leave it null if not set, but that is a bigger change. Based on that I think we'll have to go with the error checking logic, but I think we should do the following as part of this PR.

- Add warning comment in the code that it's a temporary workaround
- Add issue to track adding a new resource for vulnerability alerts, adding a new `ignore_vulnerability_alerts` field and deprecating `vulnerability_alerts` & `ignore_vulnerability_alerts_during_read` for `v6.10.0`
- Add issue to track removal of `ignore_vulnerability_alerts`, `vulnerability_alerts` & `ignore_vulnerability_alerts_during_read` for `v7.0.0`

Comment (deiga) [reply github/resource_github_repository.go:1259]: @stevehipwell Done!

I've added #3038 and #3039 could you assign them to correct milestones?

**Review by stevehipwell — APPROVED** [review]
LGTM

**Review by nickfloyd — APPROVED** [review]
